version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: auction-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: real-time-auction_db
    ports:
      - '5439:5432'
    volumes:
      - ./docker/data/dev:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15-alpine
    container_name: auction-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: real-time-auction_test
    ports:
      - '5438:5432'
    volumes:
      - ./docker/data/test:/var/lib/postgresql/data
